### ISSUE TITLE
[BUG] ISO9681 format conversion does not work with pandas 1.5.3

### ISSUE THREAD

**Issue by dngoldberg** [simon-m-mudd/nfrapy#4]
pd_todatetime() seems to fail when using format="ISO8601", and pandas<2.

a formatting string needs to encompass both daily data ("YYYY-MM-DD" and "YYYY-MM-DD HH:MM:SS" (and possibly others).

suggest format="%Y-%m-%dT%H:%M:%S.%f" as a replacement in _build_ts.

**Comment by simon-m-mudd** [comment]
Fixed with a test of pandas version 
updated in nrfapy 0.3
